### PR TITLE
Merge #243, #244 to prod

### PR DESCRIPTION
**Pull request by raphaeldussin**
@scottyhq is it ok to merge this? or will it break your cluster?

### CODE REVIEW

**Comment by raphaeldussin** [comment]
looks like it would :(

**Comment by rabernat** [comment]
Advice from @yuvipanda from gitter on naming for these PRs:

> The convention I usually use for title is to say 'Merge #x, #y to prod', where #x and #y are the staging PRs (you can see this from the commit list) that are being merged

**Comment by scottyhq** [comment]
Thanks for checking @raphaeldussin. Go ahead and merge. We are going to revamp the nasa deployment a bit. This does illustrate a potential issue though with multiple clusters in one repo. If merged staging changes are ready for one deployment but not another, what to do? Seems like if we had separate staging branches we could do merge ‘ocean-staging’ to ‘prod’? Not sure if this would be feasible with hubploy

**Comment by yuvipanda** [comment]
re: Multiple hubs in one repo, there's discussion in https://github.com/berkeley-dsep-infra/datahub/issues/660 on how to solve this.

**Pull request merged**
