### PR TITLE
Dask Gateway 0.7.1 on prod hubs

### PR DESCRIPTION
**Pull request by scottyhq**
@TomAugspurger, @tjcrone, @rabernat - currently we are running dask-gateway 0.7.1 on binders and staging hubs but still have dask-gateway 0.6 config on prod. It would be nice to merge recent changes to keep everything consistent. Is everything working as expected now on the staging hubs on GCP and Azure?

### CODE REVIEW

**Comment by TomAugspurger** [comment]
dev-staging and ocean-staging both seem fine (creating, connecting to, and scaling a Dask-Gateway cluster). hydro-staging seems to be  having trouble creating a cluster. Haven't looked closely yet. Is hydro being used?

**Comment by tjcrone** [comment]
I think everything is working on Azure. I'm ready to try this when you are. Thanks!

**Comment by scottyhq** [comment]
Ok, I'm in favor of merging this today. `hydro` and `hub` usage is being discussed here https://github.com/pangeo-data/pangeo-cloud-federation/issues/599

**Comment by TomAugspurger** [comment]
Ready whenever.

**Comment by TomAugspurger** [comment]
Did everything... just work? dev.pangeo.io seems OK.

**Comment by scottyhq** [comment]
Yes! 🎉 aws working like a charm

**Comment by rabernat** [comment]
Sorry I'm late to the party. Just tried on ocean prod. Dask gateway is working, including dashboard! 😁

**Pull request merged**
