### PR TITLE
Update ooi whitelist

### PR DESCRIPTION
**Pull request by lsetiawan**
Adding myself to OOI whitelist since org whitelist doesn't work.

### CODE REVIEW

**Comment by lsetiawan** [comment]
ping @tjcrone This is needed because you're using people whitelist, not just organization. I think to change this behaviour this config needs to be updated so that you don't use user whitelist. Thanks!

**Comment by tjcrone** [comment]
@lsetiawan, are you saying that it is not possible to mix a user whitelist with the organization whitelist?

**Comment by tjcrone** [comment]
If this is the case, can you please instead update this PR so that you remove the user whitelist section entirely?

**Comment by lsetiawan** [comment]
@tjcrone I have updated with the config suggested.

**Pull request merged**
