### PR TITLE
Bump worker resource limits to match ocean

### PR DESCRIPTION
**Pull request by TomAugspurger**
cc @chiaral.

This also changes the values for icesat & ooi (@scottyhq & @tjcrone). Hopefully that's OK. If not I'll followup with a commit lowering them again.

### CODE REVIEW

**Comment by rabernat** [comment]
This is working for @chiaral in the sense that it is giving her workers with more memory (she's using `worker_memory=14`). However, it looks like those workers are going into the core pool!

image

**Comment by chiaral** [comment]
Hello, just logged on staging of the new "ocean" and tried to run the usual 
```
import dask_gateway
gateway = dask_gateway.Gateway()
options = gateway.cluster_options() 
options.worker_memory=12
```
and I get again the error
`ValueError: worker_memory must be <= 8.000000, got 11.5`

Ryan made me notice that it seems like it should be changed 
https://github.com/pangeo-data/pangeo-cloud-federation/blob/3cfaf4c7d195310e15310d3dc8890e20b5e2e6c7/pangeo-deploy/values.yaml#L80-L84

but for some reason I get this error.

Is there something i am doing wrong?

**Comment by TomAugspurger** [comment]
Mmm it’s quite likely that I dropped the update to the limits when I copy pasted the config. Will push a fix quick.

**Comment by TomAugspurger** [comment]
Updated staging in 6b44f08f49fc2244412382391adea317b6777947.

It's deploying now.

**Comment by chiaral** [comment]
Now I get a 
`ClientResponseError: 503, message='Service Unavailable', url=URL('` 
error if I try to run the same thing.

In particular, I can do:
```
import dask_gateway
gateway = dask_gateway.Gateway()
```
but whatever call I try from gateway, I get that error, with different url.

for example:
`options = gateway.cluster_options() `
gives me
`ClientResponseError: 503, message='Service Unavailable', url=URL('https://staging.us-central1-b.gcp.pangeo.io/services/dask-gateway/api/v1/options')`

`cluster = gateway.new_cluster()`
gives me
`ClientResponseError: 503, message='Service Unavailable', url=URL('https://staging.us-central1-b.gcp.pangeo.io/services/dask-gateway/api/v1/clusters/')`

maybe I just have to wait a little longer?

**Comment by TomAugspurger** [comment]
Sorry, another copy-paste issue :/

Should be fixed now!

**Comment by chiaral** [comment]
Yeah!!!! I can run these lines now and get no error! I will start playing with it.

thanks SO MUCH!

**Pull request merged**
