### PR TITLE
Bump notebook image on prod

### LINKED ISSUE #923: Tab autocomplete not working
I noticed that tab autocomplete is not working in the cloud deployment. This is quite annoying, but like a major problem. I had recently experienced the same problem on my personal computer, and the following solution fixed it for me: 

> I recently upgraded all my packages and autocomplete using tab just stopped working. This has happened to me a few times on different environments and machines, and not sure if it is the same problem everytime (but the level of annoyance is the same). But finally a solution worked for one case. Seems like usually the problem comes from a package called jedi, and for some reason the latest version of this package has the problem but not older versions (https://github.com/jupyter/notebook/issues/2435 scroll to bottom). So downgrading solved the issue for me this time (
`pip install jedi==0.17.2`)

### PR DESCRIPTION
**Pull request by scottyhq**
Should close #923

### CODE REVIEW

**Comment by scottyhq** [comment]
CI is failing on AWS b/c we rotated access keys last week and forgot to update them in this repo...

**Comment by scottyhq** [comment]
@TomAugspurger @tjcrone looks like both GCP and Azure 'failed' deploying to staging... but maybe worked? I'm surprised the OOI deploy step even ran since the PRs only changed AWS and GCP images. I thought we had things set up to run separately. In any case wanted to check things are ok before merging this PR

https://app.circleci.com/pipelines/github/pangeo-data/pangeo-cloud-federation/1691/workflows/fb5e1d10-ef2c-4279-b6db-a96c57611d1a/jobs/1858

**Comment by TomAugspurger** [comment]
Let me push a PR to staging fixing the first issue with helm.

**Comment by TomAugspurger** [comment]
OK, GCP should be good now @scottyhq.

@tjcrone thoughts on how handle OOI for now? The error is

```
Error: UPGRADE FAILED: another operation (install/upgrade/rollback) is in progress
```

So it'd need someone with kubernetes access to debug. Should we just comment it out from the deploy?

**Comment by TomAugspurger** [comment]
Ah, but https://app.circleci.com/pipelines/github/pangeo-data/pangeo-cloud-federation/1698/workflows/44c7447d-fae2-4676-ab05-2d17d538129b/jobs/1865 apparently succeeded fine. Strange.

**Comment by scottyhq** [comment]
perhaps it's an intermittent thing. I just signed into staging.ooi.pangeo.io and it seems to be working, so i'm going to go ahead and merge.

**Pull request merged**
