### PR TITLE
bump to helm 3

### PR DESCRIPTION
**Pull request by TomAugspurger**
xref https://github.com/pangeo-data/pangeo-cloud-federation/issues/542

### CODE REVIEW

**Comment by tjcrone** [comment]
Thank you. I'm ready to merge this as long as you are happy with the current version of hubploy in requirements.txt. Not sure if you tested with the latest hubploy commit on master, which broke things for us previously: https://github.com/pangeo-data/pangeo-cloud-federation/issues/533.

**Comment by tjcrone** [comment]
Let's try it.

**Comment by tjcrone** [comment]
I think we can remove: https://github.com/pangeo-data/pangeo-cloud-federation/blob/b01e267bdb1e8be6249e442c3c61430c120f6fd6/.circleci/config.yml#L232
But not sure if that is the only thing wrong.

**Comment by TomAugspurger** [comment]
Will do a followup to fix the failures.

```
#!/bin/bash -eo pipefail
curl https://get.helm.sh/helm-v3.0.3-darwin-amd64.tar.gz | \
  tar -xzf -
sudo mv linux-amd64/helm /usr/local/bin
helm init --client-only
helm repo add pangeo https://pangeo-data.github.io/helm-chart/
helm repo add jupyterhub https://jupyterhub.github.io/helm-chart/
helm repo add dask-gateway https://dask.org/dask-gateway-helm-repo/
helm repo update
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 12.1M  100 12.1M    0     0  31.8M      0 --:--:-- --:--:-- --:--:-- 31.9M
mv: cannot stat 'linux-amd64/helm': No such file or directory
Exited with code exit status 1
CircleCI received exit code 1
```

**Pull request merged**
