### PR TITLE
Metrics and Scheduling fixes, AWS image and actions fixes

### PR DESCRIPTION
**Pull request by scottyhq**
@TomAugspurger - would love to merge this in ASAP. Took me a while to fix up the AWS github actions to use the same image pinning strategy as GCP (summary here https://github.com/pangeo-data/pangeo-cloud-federation/pull/864). Not sure if you're ready to merge in the other changes?

### CODE REVIEW

**Comment by scottyhq** [comment]
also unclear on the merge conflicts... does this happen if there were direct commits to `prod` branch previously?

**Comment by TomAugspurger** [comment]
GCP Should be good whenever.

Were there commits to prod that didn't go through staging? There shouldn't be any conflicts if everything goes through staging.

**Comment by scottyhq** [comment]
> Were there commits to prod that didn't go through staging? There shouldn't be any conflicts if everything goes through staging.

I'm flummoxed. prod is '20 commits' behind staging and there are 20 commits here to merge. I thought i fixed things by keeping differences from the staging branch (basically whitespace changes and deploying to 'metrics' namepspace). hopefully we can figure this out on Monday

**Comment by TomAugspurger** [comment]
Strange. I’ll be offline most of the next few days. You may need to edit the GitHub repo settings to get this resolvable.

**Comment by scottyhq** [comment]
Well, I just removed the requirement for 'require linear history' on `prod` and re-enabled the standard 'merge commit' option and I can proceed with this.  So we're back to the old workflow for now. Perhaps we can try again in any subsequent PRs to `squash and merge` into staging and then `rebase merge into prod` cc @TomAugspurger @tjcrone ...

**Comment by TomAugspurger** [comment]
Agreed that’s the best option, but I’m not too optimistic about remembering the separate rules for the different branches :)

**Comment by scottyhq** [comment]
Yeah, and it's likely that has to be strictly followed from the beginning. We're back to the confusing `This branch is 3 commits ahead, 2 commits behind staging.` for `prod` currently...

**Pull request merged**
