### PR TITLE
staging -> prod (long list of PRs)

### PR DESCRIPTION
**Pull request by jhamman**
Includes #503, #504, #504, #506, #507, #511, #512, #514, #515, #516, #518, #519, #520, #521, and #522

@TomAugspurger - any reason to hold on this merge?

### CODE REVIEW

**Comment by TomAugspurger** [comment]
Things should be OK. Not sure why there's a merge conflict though.

**Comment by jhamman** [comment]
@TomAugspurger - I'm not sure why there is this conflict either. They seem to be related to dask-gateway so would you mind advising on how to resolve them? The conflicts are:

```diff
<<<<<<< staging
    options:
      image: '{JUPYTER_IMAGE_SPEC}'
=======
    image: ${JUPYTER_IMAGE_SPEC}
>>>>>>> prod
```
and
```diff
<<<<<<< staging
      extraConfig:
        # Use the mapping form, to support merging multiple values.yaml
        optionHandler: |
          from dask_gateway_server.options import Options, Integer, Float, String

          def option_handler(options):
              if ":" not in options.image:
                  raise ValueError("When specifying an image you must also provide a tag")
              return {
                  "worker_cores_limit": options.worker_cores,
                  "worker_cores": min(options.worker_cores / 2, 1),
                  "worker_memory": "%fG" % options.worker_memory,
                  "image": options.image,
              }
          c.DaskGateway.cluster_manager_options = Options(
              Integer("worker_cores", 2, min=1, max=4, label="Worker Cores"),
              Float("worker_memory", 4, min=1, max=8, label="Worker Memory (GiB)"),
              String("image", default="pangeo/base-notebook:2019.12.24", label="Image"),
              handler=option_handler,
          )

        userLimts: |
          c.UserLimits.max_cores = 100
          c.UserLimits.max_memory = "400 G"
          c.UserLimits.max_clusters = 1

        tlsURL: |
          if isinstance(c.DaskGateway.public_connect_url, str):
              c.DaskGateway.public_connect_url += "/services/dask-gateway"

=======
      extraConfig: |
        from dask_gateway_server.options import Options, Integer, Float, String

        def option_handler(options):
            if ":" not in options.image:
                raise ValueError("When specifying an image you must also provide a tag")
            return {
                "worker_cores_limit": options.worker_cores,
                "worker_cores": min(options.worker_cores / 2, 1),
                "worker_memory": "%fG" % options.worker_memory,
                "image": options.image,
            }
        c.DaskGateway.cluster_manager_options = Options(
            Integer("worker_cores", 2, min=1, max=4, label="Worker Cores"),
            Float("worker_memory", 4, min=1, max=8, label="Worker Memory (GiB)"),
            String("image", default="pangeo/base-notebook:2019.12.24", label="Image"),
            handler=option_handler,
        )
>>>>>>> prod
```

**Comment by TomAugspurger** [comment]
Merging prod into staging fixed things. Commit history will look a bit strange, but things should be good going forward...

**Comment by jhamman** [comment]
Thanks @TomAugspurger!

**Pull request merged**
