### PR TITLE
#330 -> [prod] (xmitgcm, xhistogram)

### PR DESCRIPTION
**Pull request by rabernat**
I would like to merge the new packages we added in #330 to the ocean production cluster.

However, trying to naively merge staging to prod brings along like 50 commits that have nothing to do with this.

There has got to be a better way. What do the experts recommend here?

### CODE REVIEW

**Comment by TomAugspurger** [comment]
> There has got to be a better way. What do the experts recommend here?

If you just want some you can branch off `prod` and cherry pick the commits you want

```
git cherry-pick -x -m 1 3e98fbb
```

But perhaps getting prod synced up with staging is a good idea.

**Comment by tjcrone** [comment]
I have been dreading this problem when thinking about how I would merge my staging into prod. I am glad we are talking about this now. My sense is that cherry picking is the wrong way to go, and that merging staging into prod should be the solution we are looking for. But it's a little scary since they are so far apart. @jhamman or @scottyhq do you have any thoughts? Is there a reason we cannot merge staging into prod?

**Comment by tjcrone** [comment]
I'm sortof thinking outloud here, but I wonder if each deployment needs its own staging and deployment branch, so they can proceed at their own pace separately, and we modify CircleCI scripts accordingly. Another option would be separate repos, but separate branches is probably not too difficult to deal with. I will defer to the experts as well.

**Comment by scottyhq** [comment]
First of all, no problem from my point of view if you just go ahead with this @rabernat 

That said I'm also in favor of brainstorming some restructuring! Maybe we move the discussion to this existing issue? https://github.com/pangeo-data/pangeo-cloud-federation/issues/308 

> I'm sortof thinking outloud here, but I wonder if each deployment needs its own staging and deployment branch, so they can proceed at their own pace separately, and we modify CircleCI scripts accordingly. Another option would be separate repos, but separate branches is probably not too difficult to deal with. I will defer to the experts as well.

I like this idea. I'm going to ping @yuvipanda for his thoughts though since he has been instrumental in setting this system up and providing guidance for how to best structure things. Also @rsignell-usgs is now officially in charge of the esip deployment...

**Comment by rabernat** [comment]
Ok I am going to just merge to prod as my group needs this asap.

Going forward we can work out a better system.

**Comment by rabernat** [comment]
So the ocean deployment to prod failed with the following error:

```
#!/bin/bash -eo pipefail
hubploy deploy ocean pangeo-deploy ${CIRCLE_BRANCH}
Activated service account credentials for: [hubploy-circleci@pangeo-181919.iam.gserviceaccount.com]
WARNING: Accessing a Kubernetes Engine cluster requires the kubernetes commandline
client [kubectl]. To install, run
  $ gcloud components install kubectl

Fetching cluster endpoint and auth data.
kubeconfig entry generated for dev-pangeo-io-cluster.
Hang tight while we grab the latest from your chart repositories...
...Unable to get an update from the "local" chart repository (http://127.0.0.1:8879/charts):
	Get http://127.0.0.1:8879/charts/index.yaml: dial tcp 127.0.0.1:8879: connect: connection refused
...Successfully got an update from the "pangeo-data" chart repository
...Successfully got an update from the "stable" chart repository
Update Complete. ⎈Happy Helming!⎈
Saving 1 charts
Downloading pangeo from repo https://pangeo-data.github.io/helm-chart/
Deleting outdated charts
Error: UPGRADE FAILED: timed out waiting for the condition
Traceback (most recent call last):
  File "/home/circleci/repo/venv/bin/hubploy", line 11, in <module>
    sys.exit(main())
  File "/home/circleci/repo/venv/lib/python3.7/site-packages/hubploy/__main__.py", line 65, in main
    helm.deploy(args.deployment, args.chart, args.environment, args.namespace, args.set, args.version)
  File "/home/circleci/repo/venv/lib/python3.7/site-packages/hubploy/helm.py", line 128, in deploy
    version
  File "/home/circleci/repo/venv/lib/python3.7/site-packages/hubploy/helm.py", line 58, in helm_upgrade
    subprocess.check_call(cmd)
  File "/usr/local/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['helm', 'upgrade', '--wait', '--install', '--namespace', 'ocean-prod', 'ocean-prod', 'pangeo-deploy', '-f', 'deployments/ocean/config/common.yaml', '-f', 'deployments/ocean/config/prod.yaml', '-f', 'deployments/ocean/secrets/prod.yaml', '--set', 'pangeo.jupyterhub.singleuser.image.tag=ed457c8', '--set', 'pangeo.jupyterhub.singleuser.image.name=us.gcr.io/pangeo-181919/ocean-pangeo-io-notebook']' returned non-zero exit status 1.
Exited with code 1
```

It appears that `help upgrade` timed out. Why would this happen? It worked fine on staging?

I am about to go offline for a week. People in my group are really depending getting these new packages installed. I would sincerely appreciate it if someone could try to figure out what is wrong here.

**Comment by rabernat** [comment]
The hyrdo prod deployment also failed in the same way.

https://circleci.com/gh/pangeo-data/pangeo-cloud-federation/634

**Comment by tjcrone** [comment]
Ryan, Are you working on the ocean deployment or the dev (hub) deployment? If you only need to deploy on hub, we can comment the others out of the CircleCI config for the time being.

**Comment by tjcrone** [comment]
I have a PR that does this.

**Comment by tjcrone** [comment]
Nevermind. I see that the dev deployment worked. If this is what you wanted @rabernat, then you should be good to go. I see those timeout issues all the time, and I usually fix them by running helm commands manually. I don't have access to these clusters or deployments so we might need to wait for @scottyhq for assistance.

But this issue was what I was worried about. I think that separate branches (two each) for each deployment would likely solve this. It makes much more sense to me to build/deploy only for the deployment we are working on.

**Comment by rabernat** [comment]
I am trying to deploy ocean.pangeo.io with a few new packages (see #330).

The deploying to staging worked fine. The deployment to prod failed with a `help upgrade` timeout. This is beyond by debugging ability.

**Comment by tjcrone** [comment]
I think if you roll back to a previous working release, we can try to run the workflow again. The timeout issue is often related to slow image pulls, for whatever reason that happens. But when you try again the image is already there so it works. Can you roll ocean.pangeo.io back to a previous release using helm commands on the command line?

**Comment by rabernat** [comment]
Someone (not me) ran the workflow again and it failed with a different error:
```
Fetching cluster endpoint and auth data.
kubeconfig entry generated for dev-pangeo-io-cluster.
Hang tight while we grab the latest from your chart repositories...
...Unable to get an update from the "local" chart repository (http://127.0.0.1:8879/charts):
	Get http://127.0.0.1:8879/charts/index.yaml: dial tcp 127.0.0.1:8879: connect: connection refused
...Successfully got an update from the "pangeo-data" chart repository
...Successfully got an update from the "stable" chart repository
Update Complete. ⎈Happy Helming!⎈
Saving 1 charts
Downloading pangeo from repo https://pangeo-data.github.io/helm-chart/
Deleting outdated charts
Error: UPGRADE FAILED: no DaemonSet with the name "continuous-image-puller" found
Traceback (most recent call last):
  File "/home/circleci/repo/venv/bin/hubploy", line 11, in <module>
    sys.exit(main())
  File "/home/circleci/repo/venv/lib/python3.7/site-packages/hubploy/__main__.py", line 65, in main
    helm.deploy(args.deployment, args.chart, args.environment, args.namespace, args.set, args.version)
  File "/home/circleci/repo/venv/lib/python3.7/site-packages/hubploy/helm.py", line 128, in deploy
    version
  File "/home/circleci/repo/venv/lib/python3.7/site-packages/hubploy/helm.py", line 58, in helm_upgrade
    subprocess.check_call(cmd)
  File "/usr/local/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['helm', 'upgrade', '--wait', '--install', '--namespace', 'ocean-prod', 'ocean-prod', 'pangeo-deploy', '-f', 'deployments/ocean/config/common.yaml', '-f', 'deployments/ocean/config/prod.yaml', '-f', 'deployments/ocean/secrets/prod.yaml', '--set', 'pangeo.jupyterhub.singleuser.image.tag=ed457c8', '--set', 'pangeo.jupyterhub.singleuser.image.name=us.gcr.io/pangeo-181919/ocean-pangeo-io-notebook']' returned non-zero exit status 1.
Exited with code 1
```

Here is the latest `helm history ocean-prod`
```
                    
24      	Sat Jun 15 06:33:51 2019	DEPLOYED  	pangeo-deploy-0.1.0	Upgrade complete                                            
25      	Fri Jul 19 11:30:52 2019	FAILED    	pangeo-deploy-0.1.0	Upgrade "ocean-prod" failed: timed out waiting for the co...
26      	Fri Jul 19 13:01:04 2019	FAILED    	pangeo-deploy-0.1.0	Upgrade "ocean-prod" failed: no DaemonSet with the name "...
```

@tjcrone - are you suggesting I run `helm rollback ocean-staging 24`?

**Comment by rabernat** [comment]
Rolling back had no effect on the helm history, since neither of the new releases (25 or 26) actually deployed.

So we are now stuck on
```
Error: UPGRADE FAILED: no DaemonSet with the name "continuous-image-puller" found
```
Both ocean and hydro are failing to deploy because of this error.

This is one for the kubernetes gurus.

**Comment by tjcrone** [comment]
Are you saying that rolling back to 24 did not work?

**Comment by tjcrone** [comment]
Also when it is deploying a PR to the prod branch, it is not trying to deploy to ocean-staging. You should be looking at the production deployment and rolling that back to the last good one.

**Comment by rabernat** [comment]
> You should be looking at the production deployment and rolling that back to the last good one.

Good catch! I was running `helm history ocean-prod` but then rolling back `ocean-staging`. Dumb mistake!

After rolling back correctly, it looks like it we are headed for a timeout again.

**Comment by rabernat** [comment]
So there appear to be two separate issues here:
- Standard `helm upgrade` is timing out after 5 minutes
- After that fails, future updates fail with `Error: UPGRADE FAILED: no DaemonSet with the name "continuous-image-puller" found` and the release has to be rolled back manually (`helm rollback ocean-prod 24`)

I am about to disappear on sailboat for a week. I would love it if someone else could fix this.

**Comment by rabernat** [comment]
Actually, the last time around, after rolling back and re-running the workflow, ocean prod finally deployed!

**Comment by tjcrone** [comment]
Fantastic! Glad it worked out. Have a nice sailing trip.

**Pull request merged**
