### PR TITLE
turn on userScheduler again

### PR DESCRIPTION
**Pull request by jhamman**
xref: #273

@consideRatio - do you think we need the userPlaceholder feature at this point?

### CODE REVIEW

**Comment by consideRatio** [comment]
Hmmm in short, for both a good up (user placeholders) and down (user scheduler) scaling experience, enable at least one user placeholder and pod priority as well. For more details see the [optimization section](http://z2jh.jupyter.org/en/latest/optimization.html) of the z2jh guide for details.

- If you don't have the user scheduler enabled, you won't get nodes packed tight, which really matters in order to help with downscaling.
- If you don't have user placeholders enabled and >0 replicas of them, you won't scale up the jupyter user nodes ahead of time, that will user need to wait for example 4-8 minutes when they scale up.
- NOTE: enabling user-placeholder pods requires you to enable podpriority as well, and that should only be done on k8s 1.11+. Furthermore, some technical details may differ in between cloud provider at least before k8s 1.13.

**Comment by consideRatio** [comment]
LGTM @jhamman !

If you have non GKE clusters, I'd verify the following regarding the podPriority setting, that is not a given to work on all different K8s clusters of versions that isn't super fresh, but will work great on GKE at least. I know little about AWS / Azure etc. though.

1. What is the priority given pods in general?
2. What is the priority given to of user-placeholder pods?
3. What is the priority cutoff of the cluster? This will depend and be hard to inspect, so I'd simply try verifying that it is possible to evict user-placeholder pods with normal users. One way to see if this happens is to see that they first manage to schedule somewhere, and then becomes pending, and then schedules on another node and get their running time reset.

**Comment by consideRatio** [comment]
Disclaimer and a rule of thumb I conjure out of the air: having user placeholders is probably a bad idea if you want to scale down to 0 nodes, but a good idea if you don't.

**Comment by jhamman** [comment]
> Disclaimer and a rule of thumb I conjure out of the air: having user placeholders is probably a bad idea if you want to scale down to 0 nodes, but a good idea if you don't.

Yes, we do want to scale down to zero nodes (for now). That's why I was previously disabling this feature.

**Comment by jhamman** [comment]
@scottyhq - can you remind me what version of k8s the two aws clusters are running?

**Pull request merged**
