### PR TITLE
ocean image tweaks

### LINKED ISSUE #6: cloud environment: fsspec to master?
We were having trouble reading zarr stores on Google:
    https://github.com/intake/filesystem_spec/issues/157

Does fsspec/master solve the problem?

### PR DESCRIPTION
**Pull request by jhamman**
- updates base image
- points to dev/master branches of xgcm, fspec, intake-esm

cc @martindurant, @andersy005, @jbusecke, @rabernat 

closes https://github.com/cmip6hack/project-template/issues/6

### CODE REVIEW

**Comment by andersy005** [comment]
@jhamman, we may need to add the master branch of gcsfs as well.

**Comment by andersy005** [comment]
And I am hoping to cut a new release of intake-esm tomorrow (Tuesday :))

**Comment by rabernat** [comment]
Should we wait until intake-esm is released to merge this?

**Comment by rabernat** [comment]
I see that the google cloud bucket now has two items:

- https://storage.googleapis.com/pangeo-cmip6/glade-cmip6.csv.gz
- https://storage.googleapis.com/pangeo-cmip6/pangeo-cmip6-zarr-consolidated-stores.csv

@charlesbluca - is this working? Do you need me to set any CORS or mime-type properties on the google cloud bucket?

**Comment by jhamman** [comment]
Let's merge this now so we can evaluate the possible fix to #448.

**Pull request merged**
