### PR TITLE
bump image version

### PR DESCRIPTION
**Pull request by TomAugspurger**

### CODE REVIEW

**Comment by TomAugspurger** [comment]
cc @jhamman this should fix #500, at least for staging.

I think we'll need to manually delete the dask-gateway deployments on prod before merging staging into prod.

**Comment by jhamman** [comment]
Thanks @TomAugspurger! This bump worked on the redeploy. Can you repeat the steps for prod?

**Comment by TomAugspurger** [comment]
@jhamman it looks like prod is on dask-gateway 0.6.0, so that shouldn't be necessary. I'll keep an eye out for a similar failure next time prod is deployed though.

**Comment by jhamman** [comment]
Thanks. I'll setup a prod bump now.

**Pull request merged**
