### PR TITLE
staging -> prod (#477, #478, #480, #481, #482, #484, #486, #493, #494) 

### PR DESCRIPTION
**Pull request by rabernat**
fixes https://github.com/pangeo-data/pangeo-datastore/issues/74
fixes https://github.com/pangeo-data/pangeo-datastore/issues/73
fixes https://github.com/pangeo-data/pangeo/issues/754

### CODE REVIEW

**Comment by jhamman** [comment]
It looks like I need to add the gateway secrets for the prod deployments. I'll try to do that now.

**Comment by jhamman** [comment]
@tjcrone - I added the dask-gateway secrets for the prod clusters on the google hubs. Can you make sure the ooi hub has the correct secrets? I don't have the git-crypt key for the ooi deployment.

**Comment by rabernat** [comment]
Anything I can do to anything I can do to help here? 

Our entire data catalog is broken until we can deploy this.

**Comment by jhamman** [comment]
@rabernat - We need to hear from @tjcrone to make sure the OOI cluster can handle this merge.  We also need to sort out why the builds are timing out.

**Comment by rabernat** [comment]
> We also need to sort out why the builds are timing out.

To get around this for ocean, I added this:

https://github.com/pangeo-data/pangeo-cloud-federation/blob/b52b55970622911fcacc6ca9d34fb657af35b682/.circleci/config.yml#L55-L58

The bigger question is, why does it now take 35 minutes to build these images? 🤦‍♂

**Comment by tjcrone** [comment]
I'm watching this and prepared to help. We are in a good spot in terms of a merge that might break our deployment. Shouldn't be a problem this week. Thank you very much for checking. Please go ahead and merge if you can, and if something goes wrong with our deployment, I will fix it.

**Comment by tjcrone** [comment]
I have updated our secrets on our fork, but I'm not sure how to add these to this PR. Let's go ahead and merge this, and then I will do a separate PR to merge our secrets files. Does this sound reasonable? We are fine on our side for any merge you decide to do here. Thank you again!

**Pull request merged**
