### PR TITLE
change ocean2 to ocean

### PR DESCRIPTION
**Pull request by raphaeldussin**

### CODE REVIEW

**Comment by rabernat** [comment]
What changes were made to secrets?

**Comment by raphaeldussin** [comment]
secrets are set to your globus client id/secret from mine

**Comment by rabernat** [comment]
probably callback URL I guess

**Comment by raphaeldussin** [comment]
merge?

**Comment by rabernat** [comment]
So the secrets should look like this

```
pangeo:
  jupyterhub:
    proxy:
      secretToken: b8...3
    auth:
      type: globus
      globus:
        clientId: "af...a"
        clientSecret: "mI...="
        callbackUrl: "https://ocean.pangeo.io/hub/oauth_callback"
        identityProvider: "orcid.org"
      admin:
        access: true
        users:
          - "0000-0001-7479-8439" # Joe Hamman
          - "0000-0001-5999-4917" # Ryan Abernathey
          - "0000-0003-4004-4553" # Raphael Dussin
```

If you can confirm, I will merge.

**Comment by raphaeldussin** [comment]
yes, all good!

**Pull request merged**
