### PR TITLE
staging -> prod

### PR DESCRIPTION
**Pull request by TomAugspurger**

### CODE REVIEW

**Comment by TomAugspurger** [comment]
@salvis2 AWS is failing with

```
#!/bin/bash -eo pipefail
AWS_SHARED_CREDENTIALS_FILE=./deployments/icesat2/secrets/aws-config.txt
RUNNERIP=`curl --silent https://checkip.amazonaws.com`
aws --version
aws eks update-cluster-config --region us-west-2 --name pangeo --resources-vpc-config publicAccessCidrs=${RUNNERIP}/32 > /dev/null
sleep 120

aws-cli/1.18.140 Python/3.7.2 Linux/4.15.0-1077-aws botocore/1.17.63
Unable to locate credentials. You can configure credentials by running "aws configure".
```

Are you able to take a look?

**Comment by TomAugspurger** [comment]
OOI is failing here

```
Traceback (most recent call last):
  File "/home/circleci/repo/venv/lib/python3.7/site-packages/hubploy/helm.py", line 66, in helm_upgrade
    kubernetes.config.load_kube_config(config_file=kubeconfig)
  File "/home/circleci/repo/venv/lib/python3.7/site-packages/kubernetes/config/kube_config.py", line 739, in load_kube_config
    persist_config=persist_config)
  File "/home/circleci/repo/venv/lib/python3.7/site-packages/kubernetes/config/kube_config.py", line 695, in _get_kube_config_loader_for_yaml_file
    kcfg = KubeConfigMerger(filename)
  File "/home/circleci/repo/venv/lib/python3.7/site-packages/kubernetes/config/kube_config.py", line 650, in __init__
    self.load_config(path)
  File "/home/circleci/repo/venv/lib/python3.7/site-packages/kubernetes/config/kube_config.py", line 664, in load_config
    config_merged[item] = []
TypeError: 'NoneType' object does not support item assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/circleci/repo/venv/bin/hubploy", line 11, in <module>
    load_entry_point('hubploy==0.1.1', 'console_scripts', 'hubploy')()
  File "/home/circleci/repo/venv/lib/python3.7/site-packages/hubploy/__main__.py", line 139, in main
    args.cleanup_on_fail,
  File "/home/circleci/repo/venv/lib/python3.7/site-packages/hubploy/helm.py", line 187, in deploy
    cleanup_on_fail,
  File "/home/circleci/repo/venv/lib/python3.7/site-packages/hubploy/helm.py", line 68, in helm_upgrade
    kubernetes.config.load_incluster_config()
  File "/home/circleci/repo/venv/lib/python3.7/site-packages/kubernetes/config/incluster_config.py", line 94, in load_incluster_config
    cert_filename=SERVICE_CERT_FILENAME).load_and_set()
  File "/home/circleci/repo/venv/lib/python3.7/site-packages/kubernetes/config/incluster_config.py", line 45, in load_and_set
    self._load_config()
  File "/home/circleci/repo/venv/lib/python3.7/site-packages/kubernetes/config/incluster_config.py", line 51, in _load_config
    raise ConfigException("Service host/port is not set.")
kubernetes.config.config_exception.ConfigException: Service host/port is not set.

Exited with code exit status 1
```

Probably just missing a config value in prod. Taking a look now.

**Comment by TomAugspurger** [comment]
CircleCI is also apparently running on staging. I don't understand why that would be yet.

EDIT: I guess that's normal, looking at past deployments.

**Comment by TomAugspurger** [comment]
Huh, @salvis2 in https://github.com/pangeo-data/pangeo-cloud-federation/pull/735/commits/91fb8a7570a1ea175158664dad22afcd03d7286a I reverted the recent update to hubploy. Apparently some issue authenticating with the newer version (6742809fc1d8676859fe5442478c95c41c7ad050).

OOI is still failing though.

**Comment by tjcrone** [comment]
I deleted my deployment and I'm rerunning the CI. That will likely fix OOI.

**Comment by TomAugspurger** [comment]
Thanks, seems to have passed. Here goes.

**Comment by salvis2** [comment]
@TomAugspurger what a strange thing for the CI to get hung up on. That step went fine in the prod CI action. Looks like the main Helm install timed out.

**Comment by salvis2** [comment]
OOI got the error

```
Error: rendered manifests contain a resource that already exists. Unable to continue with install: existing resource conflict: namespace: , name: ooi-prod-grafana, existing_kind: policy/v1beta1, Kind=PodSecurityPolicy, new_kind: policy/v1beta1, Kind=PodSecurityPolicy
```

which I think is something specific that @tjcrone needs to delete from the `prometheus-operator` deployment.

**Comment by TomAugspurger** [comment]
@salvis2 can you verify that aws finished successfully (even though it timed out, I think things are still running)?

I think deleting that object will fix things for OOI. I don't know why it's there in the first place though. There shouldn't be an prometheus / grafana stuff in prod I think

**Comment by salvis2** [comment]
I feel like we should be able to use a more recent version of `hubploy`. :P The one you've pinned to is https://github.com/yuvipanda/hubploy/commit/d619b2da6cae00c1b14b05b176fb66a5413eb01f, which is from March 13th. The one you changed off of is https://github.com/yuvipanda/hubploy/commit/6742809fc1d8676859fe5442478c95c41c7ad050, much more recent. I can't see the CI checks for the PR anymore, so unsure what specifically mucked things up.

**Comment by salvis2** [comment]
@TomAugspurger I launched my JHub server on the AWS hub and used the Grafana site to verify that Prometheus was passing data to it correctly. I can take a little more time and do some `kubectl` commands if you like.

**Comment by TomAugspurger** [comment]
Yeah, I'd like to stay up to date on hubploy if possible. It's strange that it didn't fail the earlier deployment.

I'm also seeing these `prod-prome-prometheus` in prod as well. Looking into it.

**Comment by tjcrone** [comment]
I deleted again. OOI should work on the next run. I hope! @salvis2, check the OOI sections of the CI config for a couple of timeout options that might be of help? I'm not sure because I cannot dig in very deep until later this afternoon.

**Comment by salvis2** [comment]
Ah, that `1200` looks mighty helpful. Thank you @tjcrone !

(For reference, the line is here: https://github.com/pangeo-data/pangeo-cloud-federation/blob/staging/.circleci/config.yml#L212)

**Comment by tjcrone** [comment]
Right. One of those timeouts is for CircleCI, and the other is for Hubploy/Helm. A timeout "waiting for the condition' is a Helm timeout. I think that's the one you got.

**Comment by salvis2** [comment]
@TomAugspurger I'll check the pods and such on AWS in a bit. Always gotta let it wait since we change the IPs that can access the cluster on every CI action (and by default it only allows UW wifi IP addresses).

**Comment by TomAugspurger** [comment]
Thanks. Once you're ready, let's redeploy to give OOI another shot.

**Comment by salvis2** [comment]
Should we try to troubleshoot `hubploy` before redeploying?

**Comment by TomAugspurger** [comment]
Either option works for me.

**Comment by salvis2** [comment]
AWS pods and services look normal.

**Pull request merged**
