### PR TITLE
Add nbdime to binder environment.yml.

### LINKED ISSUE #456: Add support for nbdime on ocean.pangeo.io
[nbdime](https://nbdime.readthedocs.io/en/latest/) is a great tool for rich visual diffs of Jupyter notebooks. It would be great to have access to this from the ocean.pangeo.io Jupyterhub / jupyterlab.

I'm preparing some tutorials on this for the CMIP6 Hackathon over here:
https://github.com/brian-rose/notebook_diff_tutorial

### PR DESCRIPTION
**Pull request by brian-rose**
Not sure if this will install the Jupyterhub / Jupyterlab extension automatically or not.

Potentially closes #456

### CODE REVIEW

**Comment by rabernat** [comment]
So now circleci is checking whether that environment can actually be built. Once that is green, I'll merge this and circleci will re-deploy http://staging.ocean.pangeo.io with the changes.

Once we are happy that it works, we can merge the `staging` branch to `prod` and the changes will hit the main cluster.

**Comment by rabernat** [comment]
Conda build is timing out! 😭 
https://circleci.com/gh/pangeo-data/pangeo-cloud-federation/901?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

Should I just restart, or is there some way we can speed up this build? Not sure why adding just one package caused this.

**Comment by jhamman** [comment]
I restarted the build. All green now.

**Comment by rabernat** [comment]
Did anyone test this on staging before merging to prod?

I saw this message today when logging in to ocean:

image


Then after running build I got this

image


I'm guessing we needed something special in our postBuild script to make nbdime work.

**Comment by rabernat** [comment]
I'm gonna merge this so we can keep iterating on the spec.

**Comment by brian-rose** [comment]
I've seen this too! nbdime *does* work after clicking on "Build" and waiting a while.

But yes surely there's a way to avoid having this pop up every time.

**Comment by TomAugspurger** [comment]
You likely need ` jupyter labextension install nbdime-jupyterlab` in the
postBuild.

**Pull request merged**
