### PR TITLE
replace any string with the correct image name

### PR DESCRIPTION
**Pull request by dsludwig**
@rsignell-usgs this should fix your issue with an out-of-date dask worker.

### CODE REVIEW

**Comment by jhamman** [comment]
Just to say, once https://github.com/dask/dask-kubernetes/pull/101 is merged, we wont need this `sed` business anymore.

**Comment by mrocklin** [comment]
I'll take another look at that PR

**Comment by rsignell-usgs** [comment]
I'm going to merge this, since @mrockin has encouraged me not to be shy on the develop branch!

**Comment by rsignell-usgs** [comment]
@dsludwig I waited until the new container was built and stopped/started my server, but the container listed in `~/.dask/config.yaml` remains the same:   the original tag of `d03a8f7`.    I will manually change it to the latest tag `d2a0adb` from the list here: https://console.cloud.google.com/gcr/images/pangeo-181919/US/dev-pangeo-io-notebook?gcrImageListsize=50

**Comment by dsludwig** [comment]
🤦‍♂️   this has the same issue as before - the `binder/start` file is not copied over, so it's still using the old file that doesn't have this change. I'll make an update to allow clobbering of home directory files.

**Pull request merged**
