### PR TITLE
bump notebook onbuild image

### PR DESCRIPTION
**Pull request by jhamman**

### CODE REVIEW

**Comment by scottyhq** [comment]
Hey @jhamman fine by me, but I think that we should first bump repo2docker in pangeo-stacks now that this is merged:
https://github.com/jupyter/repo2docker/pull/728 

Also will want to add `libconv` to our base image based on this comment https://github.com/jupyter/repo2docker/issues/758#issuecomment-518728667

**Comment by jhamman** [comment]
@scottyhq - those changes can come in a followup PR. I'd like to keep this short and sweet :)

**Comment by scottyhq** [comment]
fair enough. if they all build go ahead and merge!

**Review by scottyhq — APPROVED** [review]

**Comment by jhamman** [comment]
@scottyhq - any idea of what is up with the nasa image? https://circleci.com/gh/pangeo-data/pangeo-cloud-federation/691

**Comment by scottyhq** [comment]
It's unclear to me what the problem is. Seems like bumping repo2docker (and consequently the conda version) might fix it (https://github.com/conda/conda/issues/8831). Alternatively you can 1) remove the nasa image bump for now or 2) try removing any package in https://github.com/pangeo-data/pangeo-cloud-federation/blob/staging/deployments/nasa/image/binder/environment.yml that is already in the base image (https://github.com/pangeo-data/pangeo-stacks/blob/master/base-notebook/binder/environment.yml). 

The current setup is not ideal b/c we are pulling the base jupyter-related stuff automatically by repo2docker (see https://github.com/jupyter/repo2docker/blob/master/repo2docker/buildpacks/conda/environment.yml). Then updating with our pangeo-stacks base image. Then updating in this repo environment.yml

**Comment by jhamman** [comment]
I've gone ahead and rolled back the nasa image build. We'll have to deal with that later.

**Comment by scollis** [comment]
Something broke badly for me last night..
```
Traceback (most recent call last):
  File "/srv/conda/bin/conda-env", line 6, in <module>
    from conda_env.cli.main import main
  File "/srv/conda/lib/python3.7/site-packages/conda_env/cli/main.py", line 39, in <module>
    from . import main_create
  File "/srv/conda/lib/python3.7/site-packages/conda_env/cli/main_create.py", line 12, in <module>
    from conda.cli import install as cli_install
  File "/srv/conda/lib/python3.7/site-packages/conda/cli/install.py", line 19, in <module>
    from ..core.index import calculate_channel_urls, get_index
  File "/srv/conda/lib/python3.7/site-packages/conda/core/index.py", line 9, in <module>
    from .package_cache_data import PackageCacheData
  File "/srv/conda/lib/python3.7/site-packages/conda/core/package_cache_data.py", line 15, in <module>
    from conda_package_handling.api import InvalidArchiveError
  File "/srv/conda/lib/python3.7/site-packages/conda_package_handling/api.py", line 12, in <module>
    from .tarball import CondaTarBZ2 as _CondaTarBZ2, libarchive_enabled
  File "/srv/conda/lib/python3.7/site-packages/conda_package_handling/tarball.py", line 11, in <module>
    import libarchive
  File "/srv/conda/lib/python3.7/site-packages/libarchive/__init__.py", line 1, in <module>
    from .entry import ArchiveEntry
  File "/srv/conda/lib/python3.7/site-packages/libarchive/entry.py", line 6, in <module>
    from . import ffi
  File "/srv/conda/lib/python3.7/site-packages/libarchive/ffi.py", line 27, in <module>
    libarchive = ctypes.cdll.LoadLibrary(libarchive_path)
  File "/srv/conda/lib/python3.7/ctypes/__init__.py", line 434, in LoadLibrary
    return self._dlltype(name)
  File "/srv/conda/lib/python3.7/ctypes/__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libiconv.so.2: cannot open shared object file: No such file or directory```

**Pull request merged**
